//!Our API Key generated by TMDB 
const API_KEY = 'api_key=a17c5a8cc9908b880efecf89037b7283';
//!This is the base url that is always required whenever we are making the request to the API
const BASE_URL = 'https://api.themoviedb.org/3'

//! Our API URL is consist of three things---> base url + the main url what exactly we are fetching + API Key
const API_URL = BASE_URL + '/discover/movie?sort_by=popularity.desc&' + API_KEY;
// const API_URL = BASE_URL + '/discover/movie?primary_release_date.gte=2014-09-15&primary_release_date.lte=2014-10-22&' + API_KEY;

//!TMDB API returns the image path of movie which is required to be concatinated with this url
const IMAGE_URl = 'https://image.tmdb.org/t/p/w500';

//! This is how we search any thing from this api and at the end of it we add query parameteres
const SEARCH_URL = BASE_URL + '/search/movie?' + API_KEY

// Targetting some DOM Element
const main = document.getElementById('main');
const form = document.getElementById('form')
const search = document.getElementById('search');
const title = document.getElementById('title');
const tagsElem = document.getElementById('tags');
const generes = [
    {
        "id": 28,
        "name": "Action"
    },
    {
        "id": 12,
        "name": "Adventure"
    },
    {
        "id": 16,
        "name": "Animation"
    },
    {
        "id": 35,
        "name": "Comedy"
    },
    {
        "id": 80,
        "name": "Crime"
    },
    {
        "id": 99,
        "name": "Documentary"
    },
    {
        "id": 18,
        "name": "Drama"
    },
    {
        "id": 10751,
        "name": "Family"
    },
    {
        "id": 14,
        "name": "Fantasy"
    },
    {
        "id": 36,
        "name": "History"
    },
    {
        "id": 27,
        "name": "Horror"
    },
    {
        "id": 10402,
        "name": "Music"
    },
    {
        "id": 9648,
        "name": "Mystery"
    },
    {
        "id": 10749,
        "name": "Romance"
    },
    {
        "id": 878,
        "name": "Science Fiction"
    },
    {
        "id": 10770,
        "name": "TV Movie"
    },
    {
        "id": 53,
        "name": "Thriller"
    },
    {
        "id": 10752,
        "name": "War"
    },
    {
        "id": 37,
        "name": "Western"
    }
]
var selectedGenre = []
setGenre()
function setGenre() {
    tagsElem.innerHTML = "";
    generes.forEach((genre) => {
        const gElem = document.createElement('div');
        gElem.classList.add('tag');
        gElem.id = genre.id;
        gElem.innerText = genre.name;
        gElem.addEventListener('click', () => {
            if (selectedGenre.length == 0) {
                selectedGenre.push(genre.id);
            }
            else {
                if (selectedGenre.includes(genre.id)) {
                    selectedGenre.forEach((id, idx) => {
                        selectedGenre.splice(idx, 1);
                    })
                }
                else {
                    selectedGenre.push(genre.id);
                }
            }
            getMovies(API_URL + "&with_genres=" + encodeURI(selectedGenre.join(",")))
            highlightColor();
        })
        tagsElem.append(gElem)
    })
}

//Tags highlited when clicked and active and removed when not active
function highlightColor() {
    //By default we are removing highlight class, we are adding this class only when they are present in selectedGenre array
    const tags = document.querySelectorAll(".tag");
    tags.forEach(tag => {
        tag.classList.remove("highlight");
    });

    //whenever our highlight function is called we are calling this clear function to add clear button
    clearBtn()
    if (selectedGenre != 0) {
        selectedGenre.forEach((id) => {
            const elem = document.getElementById(id)
            elem.classList.add("highlight");
        })
    }
}


//Cear Category Button 
function clearBtn() {
    const getClear = document.getElementById('clear')
    if (getClear) {
        getClear.classList.add("highlight");
    }
    else {
        const clear = document.createElement('div')
        clear.classList.add('tag', 'highlight');
        clear.id = "clear"
        clear.innerText = "Clear X";
        clear.addEventListener("click", () => {
            selectedGenre = [];
            highlightColor();
            setGenre();
        })
        tagsElem.append(clear);
    }

}

//!Here we have created a function which is fetching the json data using fetch api and after it calling the showData funtion
getMovies(API_URL)
function getMovies(url) {
    fetch(url).then(res => res.json()).then(data => {
        // console.log(data.results)
        showMovies(data.results);
    })
}


function showMovies(data) {
    main.innerHTML = ""
    data.forEach(movie => {
        const { title, poster_path, vote_average, overview } = movie
        const movieEl = document.createElement('div');
        movieEl.classList.add('movie');
        movieEl.innerHTML = `
        <img
                src="${IMAGE_URl + poster_path}" alt = "${title}">

            <div class="movie_info">
                <h3>${title}</h3>
                <span class="${getColor(vote_average)}">${vote_average}</span>
            </div>

            <div class="overview">
                <h3>Overview</h3>
                ${overview}
            </div>
    
        `
        main.appendChild(movieEl)
    });
}

//Color according to movierating
function getColor(vote) {
    if (vote >= 8)
        return 'green';
    else if (vote >= 5)
        return 'yellow';
    else
        return 'red';
}

//Search Functionality
form.addEventListener('submit', (e) => {
    e.preventDefault()
    selectedGenre = [];
    highlightColor();
    setGenre();
    const searchTerm = search.value;
    if (searchTerm) {
        getMovies(SEARCH_URL + '&query=' + searchTerm)
    }
    else {
        getMovies(API_URL);
    }
})

//Go to home by clicking on the title of the website
title.addEventListener('click', () => {
    getMovies(API_URL);
})